EC/urls.py
from django.conf.urls import url
from django.urls import include, path
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('ecweb.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='registration/change-password.html'),),
    path('forget-password/done', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/forget-done.html'),),
    path('forget-password/', auth_views.PasswordResetView.as_view(
        template_name='registration/forget-password.html',
        success_url='done'), name='forget_password'),
    url(r'^password/reset/\
        (?P<uidb64>[0-9A-Za-z_\-]+)/\
        (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/forget-confirm.html',),
        name='password_reset_confirm',
        ),
    url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='registration/forget-complete.html'),
        name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecweb/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.home_dashboard),
    path('dashboard/', views.home_dashboard, name='home_dashboard'),
    path(
        'create-student/',
        views.create_student_view,
        name='create-student'
    ),
    path(
        'create-user/<user_type>',
        views.create_user_type_view,
        name='create-user'
    ),
    path('student/', views.user_detail, name='user_detail'),
    path('classrooms/', views.ClassRoomListView.as_view(), name='classroom_view'),
    path('classrooms/<slug:slug>/detail', views.ClassRoomDetailView.as_view(), name='classroom_detail_view'),
    path('classrooms/<slug:slug>/edit', views.ClassRoomUpdateView.as_view(), name='classroom_update_view'),
    path('classrooms/<slug:slug>/delete', views.ClassRoomDeactivateView.as_view(), name='classroom_delete_view'),
    path('classrooms/create/', views.ClassRoomCreateView.as_view(), name='classroom_create_view'),
    path('logout/', views.logout_view),
    path(
      'class/<int:class_room_id>/',
      views.list_classes_view,
      name='list_classes_view'
    ),
    path(
      'class/<int:class_id>/attendances/',
      views.class_view,
      name='class_view'
    ),
]

ecweb/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from .utils.li import (
    level_choices, 
    type_list, 
    test_choices,
    classroom_turns_choices
)
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth.models import Permission


from django.contrib.auth.models import AbstractUser


class BasicUser(AbstractUser):
    email = models.EmailField(
        _('email address'), null=False, blank=False, unique=True)

    username = models.CharField(
        _('username'),
        max_length=150,
        blank=True,
        null=True)

    avatar = models.ImageField(
        upload_to='avatars/profiles',
        default='avatars/user_default.png',
        blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class Student(models.Model):
    user = models.OneToOneField(BasicUser, on_delete=models.CASCADE)
    cod = models.IntegerField(blank=False, null=False)
    type_of_course = models.CharField(
        max_length=30, choices=type_list, blank=False, null=False)

    def __str__(self):
        return self.user.first_name


class Teacher(models.Model):
    user = models.OneToOneField(BasicUser, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.user.is_staff = True
        self.user.save()

        super(Teacher, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.first_name


class Coordinator(models.Model):
    user = models.OneToOneField(BasicUser, on_delete=models.CASCADE)

    class Meta:
        permissions = (
            ("view_all_classrooms", "Can view all classrooms"),
        )

    def save(self, *args, **kwargs):
        permission = Permission.objects.get(codename='view_all_classrooms')

        self.user.user_permissions.add(permission)
        self.user.is_staff = True
        self.user.save()

        super(Coordinator, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.first_name


class ClassRoom(models.Model):
    number_class = models.PositiveIntegerField(blank=True)
    level = models.CharField(max_length=30, choices=level_choices, blank=True)
    students = models.ManyToManyField(Student)
    teachers = models.ManyToManyField(Teacher)
    turn = models.CharField(max_length=50, choices=classroom_turns_choices)
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.__str__())
        super(ClassRoom, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('classroom_detail_view', kwargs={'slug': self.slug})

    def __str__(self):
        return '{}: {} - {}'.format(self.level, self.turn, self.number_class)


class Youtube(models.Model):
    description = models.CharField(max_length=50, blank=True)
    link = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.description


class PdfFile(models.Model):
    description = models.CharField(max_length=50, blank=True)
    file = models.FileField(upload_to="media/", blank=True)

    def __str__(self):
        return self.description


class Class(models.Model):
    classroom = models.ForeignKey(ClassRoom, on_delete=models.CASCADE)
    date = models.DateField()
    lesson = models.TextField()
    videos = models.ManyToManyField(Youtube, blank=True)
    files = models.ManyToManyField(PdfFile, blank=True)
    attendances = models.ManyToManyField(Student, blank=True)

    def __str__(self):
        return "{}: {}".format(self.date, self.lesson[:30])


class Test(models.Model):
    classroom = models.ForeignKey(ClassRoom, on_delete=models.CASCADE)
    date = models.DateField()
    type = models.CharField(max_length=50, choices=test_choices)

    def __str__(self):
        return "{}: {}".format(self.date, self.lesson[:30])


class TestGrade(models.Model):
    test_event = models.ForeignKey(Test, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    grade = models.FloatField()

ecweb/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse as r
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from datetime import date
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout
from django.contrib import messages
from django.views.generic import CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

from django.contrib.auth import logout
from .forms import PhotoForm, AttendanceForm, CreateUserForm, StudentForm
from .models import ClassRoom, Teacher, Student, Class, BasicUser, Coordinator



@login_required
def create_user_type_view(request, user_type):
    template_name = 'registration/create_user.html'
    types = ('coordinator', 'teacher')
    current_user = request.user
    if user_type not in types:
        raise Http404
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            if user_type == 'coordinator':
                Coordinator.objects.create(user=user)
            elif user_type == 'teacher':
                Teacher.objects.create(user=user)
            return redirect(r('home_dashboard'))
    else:
        form = CreateUserForm()
    context = {'form': form,
               'current_user': current_user}
    return render(request, template_name, context)


@login_required
def create_student_view(request):
    template_name = 'registration/create_student.html'
    current_user = request.user
    if request.method == 'POST':
        userform = CreateUserForm(request.POST)
        studentform = StudentForm(request.POST)
        if userform.is_valid() and studentform.is_valid():
            user = userform.save()
            student = studentform.save(commit=False)
            student.user = user
            student.save()
            return redirect(r('home_dashboard'))
    else:
        userform = CreateUserForm()
        studentform = StudentForm()
    context = {
        'userform': userform,
        'studentform': studentform,
        'current_user': current_user
    }
    return render(request, template_name, context)

  
@login_required
def home_dashboard(request):
    current_user = request.user
    user = Coordinator.objects.filter(user__id=current_user.id)

    if user:
        return render(request, 'ecweb/coordinator-dashboard.html',
                      {'coordinator': user.first(),
                       'current_user': current_user})

    user = Teacher.objects.filter(user__id=current_user.id)
    if user:
        return render(request, 'ecweb/teacher-dashboard.html',
                      {'teacher': user.first(),
                       'current_user': current_user})

    user = Student.objects.filter(user__id=current_user.id)
    if user:
        date_start = current_user.date_joined.date()
        days_con = date.today() - date_start
        days_cont_int = int(days_con.days)
        if user[0].type_of_course == "1-month":
            count_day = 30 - days_cont_int
            percent = int(-100.0 * (count_day / 30))

        else:
            count_day = 30 * 6 - days_cont_int
            percent = int(100.0 * (count_day / (30 * 6)))

        return render(request, 'ecweb/student-dashboard.html',
                      {'student': user.first(),
                       'current_user': current_user,
                       'days_cont_int': days_cont_int})

    raise Http404


@login_required
def user_detail(request):
    current_user = request.user
    insta = get_object_or_404(BasicUser, pk=int(current_user.id))

    if request.method == 'POST':
        if "change_password" in request.POST:

            form = PasswordChangeForm(request.user, request.POST)
            if form.is_valid():
                user = form.save()
                update_session_auth_hash(request, user)  # Important!
                messages.success(
                    request, 'Your password was successfully updated!')
                return redirect('user_detail')
            else:
                form = PasswordChangeForm(request.user)
                return render(request, 'ecweb/student.html', {
                    'form': form
                })

        else:

            form = PhotoForm(request.POST, request.FILES, instance=insta)
            if form.is_valid():
                profil = form.save()
                profil.user = current_user
                profil.save()

                return redirect('user_detail')
    else:
        form = PhotoForm()
        return render(request, 'ecweb/student.html',
                      {'current_user': current_user, 'form': form})


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(
                request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'registration/change-password.html', {
        'form': form
    })



def logout_view(request):
    logout(request)
    return render(request, 'registration/logout.html')


@login_required
def calendar_view(request):
    events = Calendar.objects.all()
    return render(request, 'ecweb/calendar.html', {'events': events})


class ClassRoomListView(LoginRequiredMixin, ListView):

    model = ClassRoom
    template_name = 'ecweb/classroom/classroom.html'

    def get_queryset(self):
        current_user = self.request.user

        queryset = super(ClassRoomListView, self).get_queryset()

        if current_user.is_staff:
            teacher = Teacher.objects.filter(user=current_user.id)

            if teacher.exists():
                queryset = ClassRoom.objects.filter(
                    teachers=teacher.first().id,
                    is_active=True
                )

            else:
                queryset = ClassRoom.objects.filter(is_active=True)

        else:
            student = Student.objects.get(user=current_user.id)
            queryset = ClassRoom.objects.filter(students=student.id, is_active=True)

        return queryset

class ClassRoomDetailView(DetailView):
    model = ClassRoom
    template_name = 'ecweb/classroom/detail_classroom.html'
    queryset = ClassRoom.objects.filter(is_active=True)

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        classroom = self.get_object()
        user = request.user

        is_coordinator = Coordinator.objects.filter(user=user).exists()
        student_in_classroom = classroom.students.all().filter(user=user).exists()
        teacher_in_classroom = classroom.teachers.all().filter(user=user).exists()

        if not (student_in_classroom or teacher_in_classroom or is_coordinator):
            return redirect('classroom_view')

        if not classroom.is_active:
            return redirect('classroom_view')

        return super(ClassRoomDetailView, self).dispatch(request, *args, **kwargs)

class ClassRoomCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = ClassRoom
    template_name = 'ecweb/classroom/create_classroom.html'
    success_url = reverse_lazy('classroom_view')
    permission_required = 'ecweb.view_all_classrooms'
    fields = (
        'number_class',
        'level',
        'students',
        'teachers',
        'turn'
    )

    def form_valid(self, form):

        self.object = form.save(commit=False)

        classroom_exists = ClassRoom.objects.filter(
            number_class=self.object.number_class,
            level=self.object.level,
            turn=self.object.turn,
            is_active=True
        ).exists()

        if classroom_exists:
            messages.error(
                self.request,
                'This classroom already exists.'
            )
            return super(ClassRoomCreateView, self).form_invalid(form)

        return super(ClassRoomCreateView, self).form_valid(form)

class ClassRoomUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = ClassRoom
    template_name = 'ecweb/classroom/update_classroom.html'
    permission_required = 'ecweb.view_all_classrooms'
    fields = (
        'number_class',
        'level',
        'students',
        'teachers',
        'turn'
    )

    def form_valid(self, form):

        self.object = form.save(commit=False)
        form_changed = form.has_changed()

        if form_changed:
            classroom_exists = ClassRoom.objects.filter(
                number_class=self.object.number_class,
                level=self.object.level,
                turn=self.object.turn,
                is_active=True
            ).exclude(pk=self.object.pk).exists()

            if classroom_exists:
                messages.error(
                    self.request,
                    'This classroom already exists.'
                )
                return super(ClassRoomUpdateView, self).form_invalid(form)
            else:
                messages.success(
                    self.request,
                    'Classroom successfully updated'
                )

                return super(ClassRoomUpdateView, self).form_valid(form)

        messages.info(

ecweb/templates/ecweb/classroom/classroom.html
{% extends 'ecweb/baseadmin.html' %}
{% load staticfiles %}

{% block head %}{% endblock %}

{% block js %}{% endblock %}

{% block content %}
<div class="content-wrapper">
  {% if perms.ecweb.view_all_classrooms %}
      <a href="{% url 'classroom_create_view' %}" class="btn btn-success">
        Create a classroom
      </a>
  {% endif %}
  <p>
    {% if perms.ecweb.view_all_classrooms %}
        <h4 class="text-primary mb-3">All Classrooms</h4>
    {% else %}
      <h4 class="text-primary mb-3">
        {% with total_classrooms=object_list.count %}
            My Classroom{{ total_classrooms|pluralize }}
        {% endwith %}
      </h4>
    {% endif %}
  </p>
  <div class="content-wrapper">
    {% for classroom in object_list %}
      <div class="row">
        <h3 class="text-primary col-sm-1-4">
          <a href="{% url 'classroom_detail_view' slug=classroom.slug %}">
            {{classroom.level}} - {{classroom.turn}} - {{classroom.number_class}}
          </a>
        </h3>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

ecweb/templates/ecweb/classroom/classroom_confirm_delete.html
{% extends 'ecweb/baseadmin.html' %}
{% load staticfiles %}

{% block head %}{% endblock %}

{% block js %}{% endblock %}

{% block content %}
<div class="content-wrapper">
  <form method="POST">
    {% csrf_token %}
    <div class="content-wrapper">
        <div class="row">
            <h2>Confirm delete the {{object}} classroom ?</h2>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <a href="{% url 'classroom_detail_view' slug=object.slug %}" class="btn btn-secondary">Leave</a>
            </div>
            <div class="col-sm-4">
                <button class="btn btn-danger" type="submit">Delete</button>
            </div>
        </div>
    </div>
  </form>
</div>
{% endblock %}

ecweb/templates/ecweb/classroom/create_classroom.html
{% extends 'ecweb/baseadmin.html' %}
{% load staticfiles %}

{% block head %}{% endblock %}

{% block js %}{% endblock %}

{% block content %}
<div class="content-wrapper">
  {% for message in messages %}
      {{ message }}
  {% endfor %}
  <form method="POST">
    {% csrf_token %}
    <h3>Create a classroom</h3>
    {% for field in form %}
      <div class="form-group">
        {{field.label_tag}}{{field}}
      </div>
    {% endfor %}
    <button class="btn btn-success" type="submit">Save</button>
  </form>
</div>
{% endblock %}

ecweb/templates/ecweb/classroom/detail_classroom.html
{% extends 'ecweb/baseadmin.html' %}
{% load staticfiles %}

{% block head %}{% endblock %}

{% block js %}{% endblock %}

{% block content %}
<div class="content-wrapper">
    {% for message in messages %}
        {{ message }}
    {% endfor %}
    <h3 class="text-primary mb-3">{{object.level}} - {{object.number_class}} ({{object.turn}}) </h3>
    <p>
      {% if perms.ecweb.view_all_classrooms %}
        <a href="{% url 'classroom_update_view' slug=object.slug %}" class="btn btn-info">Update</a>
        <a href="{% url 'classroom_delete_view' slug=object.slug %}" class="btn btn-danger">Delete</a>
      {% endif %}
    </p>

    <div class="classroom">
      <table class="table">
        <thead>
          <h4>Teachers</h4>
          <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
            {% for student in object.teachers.all %}
              <tr>
                <td>
                  {{student.user.first_name}}
                </td>
                <td>
                  {{student.user.last_name}}
                </td>
                <td>
                  {{student.user}}
                </td>
              </tr>
            {% endfor %}
        </tbody>
      </table>
      <table class="table">
        <thead>
          <h4>Students</h4>
          <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
            {% for student in object.students.all %}
              <tr>
                <td>
                  {{student.user.first_name}}
                </td>
                <td>
                  {{student.user.last_name}}
                </td>
                <td>
                  {{student.user}}
                </td>
              </tr>
            {% endfor %}
        </tbody>
      </table>
      <ul>
        <h2>Classes</h2>
        {% if object.class_set.all %}
          {% for class in object.class_set.all %}
            <a href="#">{{class}}</a>
          {% endfor %}
        {% else %}
          Not found.
        {% endif %}
      </ul>
    </div>
</div>
{% endblock %}

ecweb/templates/ecweb/classroom/update_classroom.html
{% extends 'ecweb/baseadmin.html' %}
{% load staticfiles %}

{% block head %}{% endblock %}

{% block js %}{% endblock %}

{% block content %}
<div class="content-wrapper">
  {% for message in messages %}
      {{ message }}
  {% endfor %}
  <form method="POST">
    {% csrf_token %}
    <h3>Update the {{object}} classroom</h3>
    {% for field in form %}
      <div class="form-group">
        {{field.label_tag}}{{field}}
      </div>
    {% endfor %}
    <button class="btn btn-success" type="submit">Update</button>
  </form>
</div>
{% endblock %}