EC/urls.py
from django.conf.urls import url
from django.urls import include, path
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('ecweb.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='registration/change-password.html'),),
    path('forget-password/done', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/forget-done.html'),),
    path('forget-password/', auth_views.PasswordResetView.as_view(
        template_name='registration/forget-password.html',
        success_url='done'), name='forget_password'),
    url(r'^password/reset/\
        (?P<uidb64>[0-9A-Za-z_\-]+)/\
        (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/forget-confirm.html',),
        name='password_reset_confirm',
        ),
    url(r'^password/reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='registration/forget-complete.html'),
        name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecweb/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.home_dashboard),
    path('dashboard/', views.home_dashboard, name='home_dashboard'),
    path(
        'create-student/',
        views.create_student_view,
        name='create-student'
    ),
    path(
        'create-user/<user_type>',
        views.create_user_type_view,
        name='create-user'
    ),
    path('student/', views.user_detail, name='user_detail'),
    path('classrooms/', views.ClassRoomListView.as_view(), name='classroom_view'),
    path('classrooms/<slug:slug>/detail', views.ClassRoomDetailView.as_view(), name='classroom_detail_view'),
    path('classrooms/<slug:slug>/edit', views.ClassRoomUpdateView.as_view(), name='classroom_update_view'),
    path('classrooms/<slug:slug>/delete', views.ClassRoomDeactivateView.as_view(), name='classroom_delete_view'),
    path('classrooms/create/', views.ClassRoomCreateView.as_view(), name='classroom_create_view'),
    path('logout/', views.logout_view),
    path(
      'class/<int:class_room_id>/',
      views.list_classes_view,
      name='list_classes_view'
    ),
    path(
      'class/<int:class_id>/attendances/',
      views.class_view,
      name='class_view'
    ),
]

ecweb/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from .utils.li import (
    level_choices, 
    type_list, 
    test_choices,
    classroom_turns_choices
)
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth.models import Permission


from django.contrib.auth.models import AbstractUser


class BasicUser(AbstractUser):
    email = models.EmailField(
        _('email address'), null=False, blank=False, unique=True)

    username = models.CharField(
        _('username'),
        max_length=150,
        blank=True,
        null=True)

    avatar = models.ImageField(
        upload_to='avatars/profiles',
        default='avatars/user_default.png',
        blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class Student(models.Model):
    user = models.OneToOneField(BasicUser, on_delete=models.CASCADE)
    cod = models.IntegerField(blank=False, null=False)
    type_of_course = models.CharField(
        max_length=30, choices=type_list, blank=False, null=False)

    def __str__(self):
        return self.user.first_name


class Teacher(models.Model):
    user = models.OneToOneField(BasicUser, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.user.is_staff = True
        self.user.save()

        super(Teacher, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.first_name


class Coordinator(models.Model):
    user = models.OneToOneField(BasicUser, on_delete=models.CASCADE)

    class Meta:
        permissions = (
            ("view_all_classrooms", "Can view all classrooms"),
        )

    def save(self, *args, **kwargs):
        permission = Permission.objects.get(codename='view_all_classrooms')

        self.user.user_permissions.add(permission)
        self.user.is_staff = True
        self.user.save()

        super(Coordinator, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.first_name


class ClassRoom(models.Model):
    number_class = models.PositiveIntegerField(blank=True)
    level = models.CharField(max_length=30, choices=level_choices, blank=True)
    students = models.ManyToManyField(Student)
    teachers = models.ManyToManyField(Teacher)
    turn = models.CharField(max_length=50, choices=classroom_turns_choices)
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.__str__())
        super(ClassRoom, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('classroom_detail_view', kwargs={'slug': self.slug})

    def __str__(self):
        return '{}: {} - {}'.format(self.level, self.turn, self.number_class)


class Youtube(models.Model):
    description = models.CharField(max_length=50, blank=True)
    link = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.description


class PdfFile(models.Model):
    description = models.CharField(max_length=50, blank=True)
    file = models.FileField(upload_to="media/", blank=True)

    def __str__(self):
        return self.description


class Class(models.Model):
    classroom = models.ForeignKey(ClassRoom, on_delete=models.CASCADE)
    date = models.DateField()
    lesson = models.TextField()
    videos = models.ManyToManyField(Youtube, blank=True)
    files = models.ManyToManyField(PdfFile, blank=True)
    attendances = models.ManyToManyField(Student, blank=True)

    def __str__(self):
        return "{}: {}".format(self.date, self.lesson[:30])


class Test(models.Model):
    classroom = models.ForeignKey(ClassRoom, on_delete=models.CASCADE)
    date = models.DateField()
    type = models.CharField(max_length=50, choices=test_choices)

    def __str__(self):
        return "{}: {}".format(self.date, self.lesson[:30])


class TestGrade(models.Model):
    test_event = models.ForeignKey(Test, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    grade = models.FloatField()

ecweb/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms
from .models import BasicUser, Student
from PIL import Image


class CreateUserForm(forms.ModelForm):
    confirm_password = forms.CharField(
        label='Confirm Password',
        max_length=128,
        widget=forms.PasswordInput()
    )

    class Meta:
        model = BasicUser
        fields = [
            'avatar', 'first_name',
            'last_name', 'email',
            'password', 'confirm_password'
        ]
        widgets = {
            'password': forms.PasswordInput()
        }

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError("Passwords don't match")
        return super(CreateUserForm, self).clean()

    def save(self, commit=True):
        user = super(CreateUserForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = ['cod', 'type_of_course']


class UpdateUserFormAdmin(CreateUserForm):
    password = auth_forms.ReadOnlyPasswordHashField(
        label=("Password"),
        help_text=(
            "Raw passwords are not stored, instead "
            "a hash is created from them, and is "
            "saved in the database. "
        )
    )


class PhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = BasicUser
        fields = ('avatar', 'x', 'y', 'width', 'height', )
        widgets = {
            'avatar': forms.FileInput(attrs={
                # this is not an actual validation! don't rely on that!
                'accept': 'image/*'
            })
        }

    def save(self):
        photo = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.avatar)
        cropped_image = image.crop((x, y, w + x, h + y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.avatar.path)

        return photo


class AttendanceForm(forms.Form):
    class_id = forms.CharField(
        label='Class id', max_length=100, widget=forms.HiddenInput())
    students = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(), required=False)

ecweb/templates/ecweb/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>English College</title>
  {% block head %}{% endblock %}
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

ecweb/templates/ecweb/baseadmin.html
{% load staticfiles %}
<DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>EC Admin</title>
    <link rel="stylesheet" href="{% static '/css/style.css' %}"/>
    <link rel="stylesheet" href="{% static '/css/libs/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static '/css/libs/perfect-scrollbar.min.css' %}" />
    <link rel="shortcut icon" href="{% static '/images/favicon.png' %}"/>
    {% block head %}{% endblock %}
  </head>
  <body>
    <div class=" container-scroller">
      <!--Navbar-->
      <nav class="navbar bg-primary-gradient col-lg-12 col-12 p-0 fixed-top navbar-inverse d-flex flex-row">
        <div class="bg-white text-center navbar-brand-wrapper">
          <a class="navbar-brand brand-logo" href="/dashboard"><img src="{% static 'images/logo_star_black.png' %}" /></a>
          <a class="navbar-brand brand-logo-mini" href="/dashboard"><img src="{% static 'images/logo_star_mini.jpg' %}" alt=""></a>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-center">
          <button class="navbar-toggler navbar-toggler hidden-md-down align-self-center mr-3" type="button" data-toggle="minimize">
            <span class="navbar-toggler-icon"></span>
          </button>

          <ul class="navbar-nav ml-lg-auto d-flex align-items-center flex-row">
            <li class="nav-item">
              <a class="nav-link profile-pic" href="#"><img class="rounded-circle" src="{{ user.avatar.url}}" alt=""></a>
            </li>
            <li class="nav-item align-self-center">
              <br><a href="/logout" style="text-decoration:none"><p class="designation">Logout</p></a>
            </li>
          </ul>
          <button class="navbar-toggler navbar-toggler-right hidden-lg-up align-self-center" type="button" data-toggle="offcanvas">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </nav>
      <!--End navbar-->
      <div class="container-fluid">
        <div class="row row-offcanvas row-offcanvas-right">
          <nav class="bg-white sidebar sidebar-fixed sidebar-offcanvas" id="sidebar">
            <div class="user-info">
              <img src="{{ user.avatar.url}}" alt="">
              <a href="/student">
              <p class="name" >{{user.first_name}}</p>
              </a>
              {% block user_title %}{% endblock %}

              <span class="online"></span>
              <a href="/logout">
              <p class="designation">Logout</p>
              </a>
            </div>
            <ul class="nav">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'classroom_view' %}">
                    <!-- <i class="fa fa-dashboard"></i> -->
                    <img src="{% static '/images/icons/1.png' %}" alt="">
                    <span class="menu-title">Classeroom</span>
                  </a>
              </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <img src="{% static '/images/icons/2.png' %}" alt="">
                    <span class="menu-title">Events</span>
                  </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                      <!-- <i class="fa fa-wpforms"></i> -->
                      <img src="{% static '/images/icons/3.png' %}" alt="">
                      <span class="menu-title">Grades</span>
                    </a>
                </li>
                {% if user.is_staff == True%}
                <li class="nav-item">
                    <a class="nav-link" href="#">
                      <!-- <i class="fa fa-calculator"></i> -->
                      <img src="{% static '/images/icons/4.png' %}" alt="">
                      <span class="menu-title">Students </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'classroom_view' %}">
                      <!-- <i class="fa fa-table"></i> -->
                      <img src="{% static '/images/icons/5.png' %}" alt="">
                      <span class="menu-title">Classrooms </span>
                    </a>
                </li>
                {% endif %}
            </ul>
          </nav>
          <!-- SIDEBAR ENDS -->

          {% block content %}{% endblock %}

          <footer class="footer">
            <div class="container-fluid clearfix">
              <span class="float-right">
                <a href="#">EC Admin</a> &copy; 2017
              </span>
            </div>
          </footer>
        </div>
      </div>
    </div>

    <script src="{% static  '/js/libs/jquery.min.js' %}"></script>
    <script src="{% static  '/js/libs/tether.min.js' %}"></script>
    <script src="{% static  '/js/libs/bootstrap.min.js' %}"></script>
    <script src="{% static  '/js/libs/Chart.min.js' %}"></script>
    <script src="{% static  '/js/libs/perfect-scrollbar.jquery.min.js' %}"></script>
    <script src="{% static  '/js/off-canvas.js' %}"></script>
    <script src="{% static  '/js/hoverable-collapse.js' %}"></script>
    <script src="{% static  '/js/misc.js' %}"></script>
    {% block js %}{% endblock %}
  </body>
</html>

ecweb/templates/ecweb/class_attendance.html
{% extends 'ecweb/baseadmin.html' %}
{% load staticfiles %}

{% block head %}


{% endblock %}

{% block js %}


{% endblock %}




{% block content %}
<div class="content-wrapper">

    Date: {{ class_obj.date }}
    <br/>
    Lessons: {{ class_obj.lesson }}

    <form action="/class/{{class_id}}/attendances/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Save attendances" />
    </form>
</div>
{% endblock %}

ecweb/templates/ecweb/classes.html
{% extends 'ecweb/baseadmin.html' %}
{% load staticfiles %}

{% block head %}{% endblock %}

{% block js %}{% endblock %}

{% block content %}
<div class="content-wrapper">
  <h1>Classes</h1>

  {% for class_obj in all_classes%}
  	  <h3 class="text-primary mb-4">{{class_obj.classroom.level}} - 
  	  
    <a href="{% url 'class_view' class_obj.id %}">{{class_obj.date}}</a>
    </h3>
  {% endfor %}
</div>
{% endblock %}

ecweb/templates/ecweb/classroom.html
{% extends 'ecweb/baseadmin.html' %}
{% load staticfiles %}

{% block head %}{% endblock %}

{% block js %}{% endblock %}


{% block content %}
<div class="content-wrapper">

	
	{% for classroom in classrooms%}
  <h3 class="text-primary mb-4">{{classroom.level}} - {{classroom.number_class}}</h3>
  <a href="{% url 'list_classes_view' classroom.id %}">link</a>
  {% endfor%}
</div>
{% endblock %}

ecweb/templates/ecweb/coordinator-dashboard.html
{% extends 'ecweb/baseadmin.html' %}
{% load staticfiles %}

{% block head %}
	<style type="text/css">
		a.btn {
			color: white;
			font-weight: bold;
		}
		a.btn.btn-coodinator {
			background-color: #005890;
		}
		a.btn.btn-coodinator:hover {
			background-color: #2b82ba;
		}
		a.btn.btn-teacher {
			background-color: #2c4a5d;
			
		}
		a.btn.btn-teacher:hover {
			background-color: #1d608a;
		}
		a.btn.btn-student {
			background-color: #238484;
		}
		a.btn.btn-student:hover {
			background-color: #59bfbf;
		}
		.row.buttons {
			margin-bottom: 10px;
			margin-left: 1em;
		}
	</style>
{% endblock %}

{% block js %}
{% endblock %}

{% block content %}
<div class="content-wrapper">
    <h3 class="text-primary mb-4">Coordinator's Dashboard</h3>
    <div class="row buttons">
	    <a class="btn btn-coodinator" 
	    	href="{% url 'create-user' user_type='coordinator' %}">
	    		Create a Coordinator
	    </a>
	</div>
	<div class="row buttons">
	    <a class="btn btn-teacher" 
	    	href="{% url 'create-user' user_type='teacher' %}">
	    		Create a Teacher
	    </a>
	</div>
	<div class="row buttons">
	    <a class="btn btn-student" 
	    	href="{% url 'create-student' %}">
	    		Create a Student
	    </a>
	</div>
</div>
<footer class="footer">
    <div class="container-fluid clearfix">
      <span class="float-right">
          <a href="#">Star Admin</a> &copy; 2017
      </span>
    </div>
</footer>
{% endblock %}

{% block user_title %}
<p class="designation">Coordinator</p>
{% endblock %}

ecweb/templates/ecweb/dashboard.html
{% extends 'ecweb/baseadmin.html' %}
{% load staticfiles %}

{% block head %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>

{% endblock %}

{% block js %}

<script type="text/javascript">
    new Chart(document.getElementById("line-chart"), {
  type: 'line',
  data: {
    labels: ["week 01",02,03,04,05,06,07,08,09,10,11,12],
    datasets: [{ 
        data: [60,60,65,60,75,80,80,70,80,95,99],
        label: "Conversation",
        borderColor: "#3e95cd",
        fill: false
      }, { 
        data: [65,70,60,60,70,85,85,75,80,80],
        label: "Listening",
        borderColor: "#8e5ea2",
        fill: false
      }, { 
        data: [50,50,65,65,80,85,90,85,80,100],
        label: "Gramar",
        borderColor: "#3cba9f",
        fill: false
      }, { 
        data: [65,70,65,70,85,80,90,90,85,95],
        label: "Reading",
        borderColor: "#e8c3b9",
        fill: false
      }
    ]
  },
  options: {

  }
});

</script>
{% endblock %}

{% block content %}
 

                
                <div class="content-wrapper">

                    <h3 class="text-primary mb-4">Student Dashboard</h3>
                    <div class="row">
                        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-6 mb-4">
                            <div class="card">
                                <div class="card-block">
                                    <h4 class="card-title font-weight-normal text-success">{{ days_cont_int }} Days</h4>
                                    <p class="card-text">Days studies</p>
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0"
                                            aria-valuemax="100">75%</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-6 mb-4">
                            <div class="card">
                                <div class="card-block">
                                    <h4 class="card-title font-weight-normal text-info">10 Days</h4>
                                    <p class="card-text ">Attendance</p>
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0"
                                            aria-valuemax="100">40%</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 mb-4">
                            <div class="card">
                                <div class="card-block">
                                    <h4 class="card-title font-weight-normal text-warning">Next Event</h4>
                                    <table class="table">
                                    <thead class="text-primary">
                                            <tr>
                                                <th>Conversetion Class</th>
                                                <th>20/12 - 17h</th>
                                                <th>Room 02</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-lg-6  mb-4">
                            <div class="card">
                                <div class="card-block">
                                    <h5 class="card-title mb-4">Progress Grade</h5>
                                    <canvas id="line-chart" style="height:250px"></canvas>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6  mb-4">
                            <div class="card">
                                <div class="card-block">
                                    <h5 class="card-title mb-4">Last Uploads</h5>
                                    <table class="table">
                                        <thead class="text-primary">
                                            <tr>
                                                <th><i class="fa fa-user ml-2"></i></th>
                                                <th>Teacher</th>
                                                <th>Name</th>
                                                <th>Item</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <th><img src="{{current_user.avatar.url}}" alt="profile" class="rounded-circle" width="40"
                                                        height="40" /></th>
                                                <td>Larry</td>
                                                <td>Verb List</td>
                                                <td><span class="badge badge-success">PDF</span></td>
                                            </tr>
                                            <tr>
                                                <th><img src="{{current_user.avatar.url}}" alt="profile" class="rounded-circle" width="40"
                                                        height="40" /></th>
                                                <td>Jonh</td>
                                                <td>news Donald Trump</td>
                                                <td><span class="badge badge-danger">Link</span></td>
                                            </tr>
                                            <tr>
                                                <th><img src="{{current_user.avatar.url}}" alt="profile" class="rounded-circle" width="40"
                                                        height="40" /></th>
                                                <td>Jonh</td>
                                                <td>Clip - RHCP</td>
                                                <td><span class="badge badge-primary">Video</span></td>
                                            </tr>
                                            <tr>
                                                <th><img src="{{current_user.avatar.url}}" alt="profile" class="rounded-circle" width="40"
                                                        height="40" /></th>
                                                <td>Larry</td>
                                                <td>Acer</td>
                                                <td><span class="badge badge-success">Success</span></td>
                                            </tr>
                                            <tr>
                                                <th><img src="{{current_user.avatar.url}}" alt="profile" class="rounded-circle" width="40"
                                                        height="40" /></th>
                                                <td>Larry</td>
                                                <td>Acer</td>
                                                <td><span class="badge badge-danger">Failed</span></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <footer class="footer">
                    <div class="container-fluid clearfix">
                      <span class="float-right">
                          <a href="#">Star Admin</a> &copy; 2017
                      </span>
                    </div>
                </footer>
            </div>
        </div>

      </div>
{% endblock %}

ecweb/templates/ecweb/events.html
{% extends 'ecweb/baseadmin.html' %}
{% load staticfiles %}

{% block content %}
<div class="content-wrapper">
<br><br><br>Events --- <br>



{% for event in events %}
<br><br>
        <tr>
          <td>{{event.title}}</td>
        </tr>

        <br><br>
{% endfor %}

</div>
{% endblock %}

ecweb/templates/ecweb/home.html
{% extends 'ecweb/base.html' %}

{% block content %}
Home
{% endblock %}

ecweb/templates/ecweb/student.html
{% extends 'ecweb/baseadmin.html' %}
{% load staticfiles %}

{% block head %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static '/css/libs/cropper.min.css' %}" rel="stylesheet">

{% endblock %}



{% block js %}
    <script src="{% static 'js/cropper.min.js' %}"></script>

    <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_avatar").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>

<script type="text/javascript">
  
(function($) {

  // $(document).ready(function() {
  
  'use strict';
  
  // find the desired selectors
  var $btn = $('#request');
  var $bio = $('#bio');
  var url = "/change-password" 
  
  // register an event
  $btn.on('click', function() {
    // hide the button
    $(this).hide();
    // send the request and get the response
    $bio.load(url);
  });
  
    
  
// });
  
})(jQuery);

</script>


{% endblock %}

{% block content %}
                <div class="content-wrapper">

                    <h3 class="text-primary mb-4">Student Dashboard</h3>

<center>
                <div class="user-info">
                    <img src="{{ current_user.avatar.url}}" class="rounded-circle" alt="" width="304" height="236">

                    <br><br><br>

<div class="container">
  <form method="post" enctype="multipart/form-data" id="formUpload">
    {% csrf_token %}
    {{ form.as_p }}


  </form>

   <!-- MODAL TO CROP THE IMAGE -->
  <div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the photo</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
          <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
        </div>
      </div>
    </div>
  </div>


</div>

                    <br><br><br>
                    <p class="name">{{current_user.first_name}}</p>
                    {% if current_user.is_staff == True%}
                    <p class="designation">Staff</p>
                    {% else %}
                    <p class="designation">Student</p>
                    {% endif %}
                    <span class="online"></span>
                </div>
                <button id="request">Change password</button>
                <div id=bio></div>
</center>
</div>
{% endblock %}